---
- hosts: localhost
  name: Gathering Facts

#   vars_prompt:
#   - name: "hostname"
#     prompt: "Cluster "
#     private: no

  tasks:
  - name: "Collecting NetApp Information"
    na_ontap_info:
      state: info
      hostname: "{{ hostname }}"
      username: "{{ ansible_env.ANSIBLE_NET_USERNAME }}"
      password: "{{ ansible_env.ANSIBLE_NET_PASSWORD }}"
      https: yes
      validate_certs: false
    register: ontap_info
  - debug:
      msg: "{{ ontap_info }}"
