---
- hosts: 127.0.0.1
  name: Gathering Facts
  vars:
    hostname: 10.20.33.210
  tasks:
  - name: "Collecting NetApp Information"
    na_ontap_info:
      state: info
      hostname: "{{ hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      https: yes
      validate_certs: false
      gather_subset: ontap_version
    register: ontap_info
  - debug:
      msg: "{{ ontap_info }}"
