---
- hosts: ansible
  name: Gathering Facts
  vars_files:
    /Users/knot/automation/ontap/secret/ontap_password.yml
  tasks:
  - name: "Collecting NetApp Information"
    na_ontap_info:
      state: info
      hostname: "{{ hostname }}"
      username: ansible
      password: "{{ ontap_password }}"
      https: yes
      validate_certs: false
    register: ontap_info
  - debug:
      msg: "{{ ontap_info }}"
