---
- hosts: control
  name: Gathering Facts

  tasks:
  - name: "Collecting NetApp Information"
    na_ontap_info:
      state: info
      hostname: "{{ hostname }}"
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      https: ye
      validate_certs: false
      gather_subset: ontap_version
    register: ontap_info
  - debug:
      msg: "{{ ontap_info }}"
