---
- name: VM INFO
  hosts: localhost
  gather_facts: no
  vars:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
  tasks:
    - name: Retreiving VM Information
      vmware_vmotion:
        hostname: '{{ hostname }}'
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: no
        folder: "/VC65.inet.local/vm/INTERNAL-OPCLOUD/STORAGE-MONITOR"
        destination_host: '{{ destination_host }}'
      delegate_to: localhost
      register: vm_info
    - debug: var=vm_info
