---
- name: VM INFO
  hosts: localhost
  gather_facts: no
  vars:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
  tasks:
    - name: Retreiving Virtual Machine Information
      vmware_vm_info:
        hostname: '{{ hostname }}'
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: no
        folder: "/VC65.inet.local/vm/INTERNAL-OPCLOUD/STORAGE-MONITOR"
      delegate_to: localhost
      register: vm_info
    - debug:
        msg: "{{item.guest_name}}: {{ item.esxi_hostname }}"
      loop: "{{ vm_info.virtual_machines }}"
