---
- name: VMOTION CLOUD ARCH VM
  hosts: localhost
  gather_facts: no
  vars:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    host_inventory: ["10.100.10.182","10.100.10.183","10.100.10.184","10.100.10.185","10.100.10.186","10.100.10.188"]
  tasks:
    - name: HOST INVENTORY
      debug: var=host_inventory

    - name: HOST VMOTION
      vmware_vmotion:
        hostname: '{{ hostname }}'
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: no
        vm_name: 'dom3-idc3-storage-monitoring'
        destination_host: '{{ destination_host }}'
      delegate_to: localhost
      register: vm
    - debug: var=vm.running_host
